### ISSUE TITLE
use SUMO to load a map

### ISSUE THREAD

**Issue by fuwen666** [RoyalSkye/AGH#1]
First of all ,thank you for your project.I would like to ask how you use SUMO to load a map and calculate the distance between two locations?Can you give some details, thanks.

**Comment by RoyalSkye** [comment]
Hi, thanks for your question. Unfortunately, this part is not handled by me. I found a tutorial [here](https://github.com/xobx-cherif/Sumo-OpenStreetMap), hope it helps!
